# Ficheiro: .github/workflows/publish.yml

name: Build and Deploy Shiny Live App

on:
  push:
    branches:
      - main  # Ou 'master', dependendo da sua branch principal

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3' # Usa uma versão específica do R

      - name: Install R Dependencies
        uses: r-lib/actions/install-deps@v2
        with:
          packages: |
            shinylive
            rsconnect

      - name: Export Shiny Live application
        run: |
          shinylive::export(appdir = ".", destdir = "docs")
        shell: Rscript {0}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
